version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    volumes:
      - ./db/init-databases.sh:/docker-entrypoint-initdb.d/init-tora-databases.sh
    ports:
      - "54320:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  agency:
    build:
      context: services/agency-service
      dockerfile: dockerfile
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy

  flat:
    build:
      context: services/flat-service
      dockerfile: dockerfile
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
