server:
  ssl:
    key-store: classpath:keystore/seerver.jks
    key-store-password: iveriver
    key-store-type: jks
    key-alias: iver
    key-password: iveriver
    enabled: true


spring:
  application:
    name: flat-service
  cloud:
    consul:
      host: localhost
      port: 8500
  jpa:
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://localhost:54320/flat
    username: flat
    password: flat
    driver-class-name: org.postgresql.Driver
logging:
  level:
    web: debug
