server:
  ssl:
    key-store: classpath:keystore/iver.p12
    key-store-password: iveriver
    key-store-type: PKCS12
    key-alias: iver
    key-password: iveriver
    enabled: true


spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://localhost:54320/flat
    username: flat
    password: flat
    driver-class-name: org.postgresql.Driver
logging:
  level:
    web: debug
