//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2023.12.23 at 02:04:43 AM MSK
//
package com.iver.agencyservice.api.v1.http.soap

import javax.xml.bind.annotation.*
import javax.xml.datatype.XMLGregorianCalendar

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "",
    propOrder = ["id", "name", "coordinatesId", "coordinatesX", "coordinatesY", "creationDate", "area", "numberOfRooms", "furnish", "view", "transport", "houseId", "houseName", "houseNumberOfFlatsOnFloor", "cost"
    ]
)
@XmlRootElement(name = "getCheapestFlatResponse")
class GetCheapestFlatResponse {
    var id: Long? = null

    @XmlElement(required = true)
    var name: String? = null

    @XmlElement(name = "coordinates.id")
    var coordinatesId: Long? = null

    @XmlElement(name = "coordinates.x")
    var coordinatesX: Int? = null

    @XmlElement(name = "coordinates.y")
    var coordinatesY: Long? = null

    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    var creationDate: XMLGregorianCalendar? = null
    var area: Int? = null
    var numberOfRooms: Int? = null

    @XmlElement(required = true)
    var furnish: String? = null

    @XmlElement(required = true)
    var view: String? = null

    @XmlElement(required = true)
    var transport: String? = null

    @XmlElement(name = "house.id")
    var houseId: Long? = null

    @XmlElement(name = "house.name", required = true)
    var houseName: String? = null

    @XmlElement(name = "house.numberOfFlatsOnFloor")
    var houseNumberOfFlatsOnFloor: Int? = null
    var cost: Double? = null

}