//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2023.12.23 at 02:04:43 AM MSK
//
package com.iver.agencyservice.api.v1.http.soap

import javax.xml.bind.annotation.*

/**
 *
 * Java class for anonymous complex type.
 *
 *
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 * &lt;complexContent>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 * &lt;sequence>
 * &lt;element name="id1" type="{http://www.w3.org/2001/XMLSchema}long"/>
 * &lt;element name="id2" type="{http://www.w3.org/2001/XMLSchema}long"/>
 * &lt;/sequence>
 * &lt;/restriction>
 * &lt;/complexContent>
 * &lt;/complexType>
</pre> *
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "", propOrder = ["id1", "id2"
    ]
)
@XmlRootElement(namespace="http://iver.com", name = "getCheapestFlatRequest")
class GetCheapestFlatRequest {
    @XmlElement(required = true)
    var id1: Long? = null
    @XmlElement(required = true)
    var id2: Long? = null
}