spring:
    application:
        name: agency-service

server:
    ssl:
        key-store: classpath:keystore/seerver.jks
        key-store-password: iveriver
        key-store-type: jks
        key-alias: iver
        key-password: iveriver
        enabled: true
    port: 8081

flat:
    api:
        url: "https://localhost:8443/flat-service-0.0.1-SNAPSHOT/api/v1/"

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/
