server:
    ssl:
        key-store: classpath:keystore/server.p12
        key-store-password: iveriver
        key-store-type: PKCS12
        key-alias: iver
        key-password: iveriver
        enabled: true
    port: 8081

flat:
    api:
        url: "https://localhost:8080/api/v1/"
