spring:
  application:
    name: zuul-server
  profiles:
    active: development
#  config:
#    import: configserver:http://admin:admin@localhost:8888
#  cloud:
#    config:
#      username: admin
#      password: admin
#      uri: http://admin:admin@localhost:8888

server:
  port: 8762
  ssl:
    key-store: classpath:keystore/seerver.jks
    key-store-password: iveriver
    key-store-type: jks
    key-alias: iver
    key-password: iveriver
    enabled: true

eureka:
  instance:
#    preferIpAddress: true
    hostname: localhost
    non-secure-port-enabled: false
    secure-port-enabled: true
    secure-port: ${server.port}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    agency-service:
      path: /agency-service/**
      serviceId: agency-service
  ssl-hostname-validation-enabled: false
  okhttp:
    enabled: true
  ignoredServices: '*'

ribbon:
  ReadTimeout: 5000000
  ConnectTimeout: 5000000
  MaxAutoRetries: 3
  MaxAutoRetriesNextServer: 3
  eureka:
    enabled: true
  OkToRetryOnAllOperations: true
  CustomSSLSocketFactoryClassName: com.netflix.http4.ssl.AcceptAllSocketFactory
  TrustStore: classpath:keystore/seerver.jks
  TrustStorePassword: iveriver
